name = "spinmachologin-org"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmachologin.org"
HMAC_KEY = "f644479a2d16ef9a90575ce05e340b0fea20c2fdc82e5d7d5cb6d67bd06d8f82"
COOKIE_NAME = "h94"
PLAY_PATH = "discover"
BUTTON_ID = "p3eeb22a6317ca91e93cfaa56a9185a10"
GATE_SALT = "a96f8c1a991b4521"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "0b50"
CTA_SELECTOR = ".play-button"
